### PR TITLE
Addition of room owners and banning functionality

### PR DESCRIPTION
**Pull request by 1337isnot1337**
This is the PR for the room owners/banning mechanisms. Feel free to look over the changes and ask me any questions, organize it the way you prefer, or just change around the code. Linted with semistandard. 

Additions: 
- Creator of a room is given Owner metadata
- Creator has a crown emoji next to their name to set them apart
- Creator sees a ban button next to each name, pressing it will permaban said player from that room in particular
- This does not apply for the default rooms

Future goals: 

- [x]  Only have creators in private rooms
- [x] Add a votekick feature to public rooms and the default rooms where a majority of players can remove another
- [x] Smooth out the code 
- [x] Add a way to mute someone's chat

### CODE REVIEW

**Comment by 1337isnot1337** [comment]
With new commits a VK button is added next to each player's name, similar to ban button. When pressing VK a 90 second cooldown activates for that user to init a VK. the VK init is announced to players, along with the total threshold. If a different player then presses the VK button for that person who the VK was initiated on, they will have voted (also cooldown). Once enough votes have occurred to meet the threshold the user is banned and cannot rejoin the room. 

- In private rooms, the owner cannot be votekicked
- In public rooms, the owner is not marked and can not ban, but if room is switched to private then owner is marked + can ban

I'm sure there's some loophole here I'm missing, lol.

**Comment by 1337isnot1337** [comment]
Finished all changes. Ready for final review/PR approval

**Comment by geoffrey-wu** [comment]
PR looks good, but I would like to test it across multiple clients and also add a description of votekicks somewhere on the page

**Comment by 1337isnot1337** [comment]
> PR looks good, but I would like to test it across multiple clients and also add a description of votekicks somewhere on the page

That is a good idea, I do not know how this would perform on other platforms although it should work regardless. For the votekicks, I think adding a paragraph on the about page would be best. Can't think of anywhere else to put it.

**Pull request merged**
